// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actions.sql

package db

import (
	"context"
)

const getAction = `-- name: GetAction :one
SELECT id, bundle_id, type, status, remote_comment_id, remote_url, receipt, attempts, created_at, executed_at, reconciled_at FROM actions WHERE id = $1
`

func (q *Queries) GetAction(ctx context.Context, id string) (Action, error) {
	row := q.db.QueryRow(ctx, getAction, id)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.BundleID,
		&i.Type,
		&i.Status,
		&i.RemoteCommentID,
		&i.RemoteUrl,
		&i.Receipt,
		&i.Attempts,
		&i.CreatedAt,
		&i.ExecutedAt,
		&i.ReconciledAt,
	)
	return i, err
}

const getActionByBundle = `-- name: GetActionByBundle :one
SELECT id, bundle_id, type, status, remote_comment_id, remote_url, receipt, attempts, created_at, executed_at, reconciled_at FROM actions WHERE bundle_id = $1
`

func (q *Queries) GetActionByBundle(ctx context.Context, bundleID string) (Action, error) {
	row := q.db.QueryRow(ctx, getActionByBundle, bundleID)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.BundleID,
		&i.Type,
		&i.Status,
		&i.RemoteCommentID,
		&i.RemoteUrl,
		&i.Receipt,
		&i.Attempts,
		&i.CreatedAt,
		&i.ExecutedAt,
		&i.ReconciledAt,
	)
	return i, err
}

const insertAction = `-- name: InsertAction :one

INSERT INTO actions (id, bundle_id, type)
VALUES ($1, $2, 'POST_ISSUE_COMMENT')
ON CONFLICT (bundle_id) DO NOTHING
RETURNING id, bundle_id, type, status, remote_comment_id, remote_url, receipt, attempts, created_at, executed_at, reconciled_at
`

type InsertActionParams struct {
	ID       string
	BundleID string
}

// actions：外部动作实例（US2 发布链）
// bundle:action 恒 1:1 由 UNIQUE(actions.bundle_id) 库级保证（review P2-3）：
// 并发插入第二个 action 被 ON CONFLICT 吞掉（无返回行），调用方回读现有行。
func (q *Queries) InsertAction(ctx context.Context, arg InsertActionParams) (Action, error) {
	row := q.db.QueryRow(ctx, insertAction, arg.ID, arg.BundleID)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.BundleID,
		&i.Type,
		&i.Status,
		&i.RemoteCommentID,
		&i.RemoteUrl,
		&i.Receipt,
		&i.Attempts,
		&i.CreatedAt,
		&i.ExecutedAt,
		&i.ReconciledAt,
	)
	return i, err
}

const markActionExecuting = `-- name: MarkActionExecuting :execrows
UPDATE actions SET status = 'EXECUTING'
WHERE id = $1 AND status = 'PENDING'
`

// PENDING → EXECUTING：0 行 = 已被他处推进，调用方取当前状态回显。
func (q *Queries) MarkActionExecuting(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markActionExecuting, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markActionFailed = `-- name: MarkActionFailed :execrows
UPDATE actions
SET status = 'FAILED', receipt = $2, executed_at = now()
WHERE id = $1 AND status = 'EXECUTING'
`

type MarkActionFailedParams struct {
	ID      string
	Receipt []byte
}

// 明确失败（GitHub 返回 4xx 类确定错误）：绝不自动重发。
func (q *Queries) MarkActionFailed(ctx context.Context, arg MarkActionFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markActionFailed, arg.ID, arg.Receipt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markActionReconciling = `-- name: MarkActionReconciling :execrows
UPDATE actions SET status = 'RECONCILING'
WHERE id = $1 AND status = 'EXECUTING'
`

// 响应丢失/网络不确定：进入核对态（AC36），等 reconcile 裁决。
func (q *Queries) MarkActionReconciling(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markActionReconciling, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markActionSucceeded = `-- name: MarkActionSucceeded :execrows
UPDATE actions
SET status = 'SUCCEEDED', remote_comment_id = $2, remote_url = $3,
    receipt = $4, executed_at = now(), reconciled_at = now()
WHERE id = $1 AND status IN ('EXECUTING', 'RECONCILING')
`

type MarkActionSucceededParams struct {
	ID              string
	RemoteCommentID *int64
	RemoteUrl       *string
	Receipt         []byte
}

// 执行成功：落回执锚点（remote_comment_id 是后续核对的身份锚，AC36）。
// EXECUTING/RECONCILING 都可以到 SUCCEEDED（后者来自核对命中）。
func (q *Queries) MarkActionSucceeded(ctx context.Context, arg MarkActionSucceededParams) (int64, error) {
	result, err := q.db.Exec(ctx, markActionSucceeded,
		arg.ID,
		arg.RemoteCommentID,
		arg.RemoteUrl,
		arg.Receipt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetActionToPending = `-- name: ResetActionToPending :execrows
UPDATE actions SET status = 'PENDING'
WHERE id = $1 AND status = 'EXECUTING'
`

// 回退为 PENDING：发布链在「从未触碰 GitHub」的步骤失败（如 preflight 的
// 基础设施错误）时使用——恢复分发据此区分「未执行，可继续」与
// 「执行过但结果未知，须核对（AC36）」。
func (q *Queries) ResetActionToPending(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, resetActionToPending, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBundleStatus = `-- name: UpdateBundleStatus :execrows
UPDATE approval_bundles SET status = $2
WHERE id = $1 AND status = $3
`

type UpdateBundleStatusParams struct {
	ID       string
	Status   string
	Status_2 string
}

// bundle 状态跟随 action 推进（APPROVED → EXECUTING → EXECUTED）。
func (q *Queries) UpdateBundleStatus(ctx context.Context, arg UpdateBundleStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBundleStatus, arg.ID, arg.Status, arg.Status_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
