// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approval_bundles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveBundle = `-- name: ApproveBundle :execrows
UPDATE approval_bundles
SET status = 'APPROVED', approved_by = $2, approved_at = now()
WHERE id = $1 AND status = 'PENDING' AND expires_at > now()
`

type ApproveBundleParams struct {
	ID         string
	ApprovedBy *string
}

// 批准：只允许 PENDING 且未过期且内容锚未变（AC32/AC33）。
// 0 行 = 状态机拒绝（已批准/已过期/内容漂移），由调用方查明原因。
func (q *Queries) ApproveBundle(ctx context.Context, arg ApproveBundleParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveBundle, arg.ID, arg.ApprovedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireBundle = `-- name: ExpireBundle :execrows
UPDATE approval_bundles SET status = 'EXPIRED'
WHERE id = $1 AND status IN ('PENDING', 'APPROVED', 'EXECUTING')
`

// 单包失效：批准前核对发现内容/目标漂移时立即翻 EXPIRED（AC33）。
// 含 EXECUTING：发布流程先占位 EXECUTING 再重核，重核失败必须能作废。
func (q *Queries) ExpireBundle(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, expireBundle, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireStaleBundles = `-- name: ExpireStaleBundles :execrows
UPDATE approval_bundles
SET status = 'EXPIRED'
WHERE status IN ('PENDING', 'APPROVED') AND expires_at < now()
`

// 过期清扫：批处理把过期的 PENDING/APPROVED 翻 EXPIRED（24h 时效，PRD §15.2）。
func (q *Queries) ExpireStaleBundles(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireStaleBundles)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApprovalBundle = `-- name: GetApprovalBundle :one
SELECT id, case_id, draft_id, action_type, target, content_digest, status, expires_at, approved_by, approved_at, idempotency_key, created_at FROM approval_bundles WHERE id = $1
`

func (q *Queries) GetApprovalBundle(ctx context.Context, id string) (ApprovalBundle, error) {
	row := q.db.QueryRow(ctx, getApprovalBundle, id)
	var i ApprovalBundle
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.DraftID,
		&i.ActionType,
		&i.Target,
		&i.ContentDigest,
		&i.Status,
		&i.ExpiresAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getApprovalBundleByIdempotencyKey = `-- name: GetApprovalBundleByIdempotencyKey :one
SELECT id, case_id, draft_id, action_type, target, content_digest, status, expires_at, approved_by, approved_at, idempotency_key, created_at FROM approval_bundles WHERE idempotency_key = $1
`

func (q *Queries) GetApprovalBundleByIdempotencyKey(ctx context.Context, idempotencyKey string) (ApprovalBundle, error) {
	row := q.db.QueryRow(ctx, getApprovalBundleByIdempotencyKey, idempotencyKey)
	var i ApprovalBundle
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.DraftID,
		&i.ActionType,
		&i.Target,
		&i.ContentDigest,
		&i.Status,
		&i.ExpiresAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const insertApprovalBundle = `-- name: InsertApprovalBundle :one

INSERT INTO approval_bundles (id, case_id, draft_id, action_type, target, content_digest, expires_at, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, case_id, draft_id, action_type, target, content_digest, status, expires_at, approved_by, approved_at, idempotency_key, created_at
`

type InsertApprovalBundleParams struct {
	ID             string
	CaseID         string
	DraftID        string
	ActionType     string
	Target         []byte
	ContentDigest  string
	ExpiresAt      pgtype.Timestamptz
	IdempotencyKey string
}

// approval_bundles：审批包（PRD §15，AC32–AC35）
// 创建审批包；idempotency_key 冲突 → 无返回行，调用方取现有包回显（AC35）。
func (q *Queries) InsertApprovalBundle(ctx context.Context, arg InsertApprovalBundleParams) (ApprovalBundle, error) {
	row := q.db.QueryRow(ctx, insertApprovalBundle,
		arg.ID,
		arg.CaseID,
		arg.DraftID,
		arg.ActionType,
		arg.Target,
		arg.ContentDigest,
		arg.ExpiresAt,
		arg.IdempotencyKey,
	)
	var i ApprovalBundle
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.DraftID,
		&i.ActionType,
		&i.Target,
		&i.ContentDigest,
		&i.Status,
		&i.ExpiresAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const rejectBundle = `-- name: RejectBundle :execrows
UPDATE approval_bundles
SET status = 'REJECTED'
WHERE id = $1 AND status = 'PENDING'
`

// 拒绝：只允许 PENDING（AC35 精神：终态不可改写）。
func (q *Queries) RejectBundle(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, rejectBundle, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
