// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package db

import (
	"context"
)

const getArtifactByDigest = `-- name: GetArtifactByDigest :one
SELECT id, run_id, kind, content_digest, size_bytes, schema_version, created_at FROM artifacts WHERE content_digest = $1
`

func (q *Queries) GetArtifactByDigest(ctx context.Context, contentDigest string) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByDigest, contentDigest)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.ContentDigest,
		&i.SizeBytes,
		&i.SchemaVersion,
		&i.CreatedAt,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :one

INSERT INTO artifacts (id, run_id, kind, content_digest, size_bytes, schema_version)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (content_digest) DO NOTHING
RETURNING id
`

type InsertArtifactParams struct {
	ID            string
	RunID         string
	Kind          string
	ContentDigest string
	SizeBytes     int32
	SchemaVersion string
}

// artifacts：不可变产物（content-addressable，正文在磁盘、库存引用与哈希）
// 同 digest = 同内容：ON CONFLICT 复用已有行（文件层天然去重，表层同样去重）。
// 冲突时无返回行（ErrNoRows），调用方经 GetArtifactByDigest 取现有 id。
func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) (string, error) {
	row := q.db.QueryRow(ctx, insertArtifact,
		arg.ID,
		arg.RunID,
		arg.Kind,
		arg.ContentDigest,
		arg.SizeBytes,
		arg.SchemaVersion,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
