// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cases.sql

package db

import (
	"context"
)

const getCase = `-- name: GetCase :one
SELECT id, repo_id, issue_number, issue_id, title, display_state, created_at, updated_at FROM cases WHERE id = $1
`

func (q *Queries) GetCase(ctx context.Context, id string) (Case, error) {
	row := q.db.QueryRow(ctx, getCase, id)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.IssueNumber,
		&i.IssueID,
		&i.Title,
		&i.DisplayState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCase = `-- name: UpsertCase :one

INSERT INTO cases (id, repo_id, issue_number, issue_id, title)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (repo_id, issue_number) DO UPDATE SET updated_at = now()
RETURNING id
`

type UpsertCaseParams struct {
	ID          string
	RepoID      string
	IssueNumber int64
	IssueID     int64
	Title       string
}

// cases：案例上下文
// Webhook 同一事务里创建/更新 case：
// 首次事件建行（title 是首次快照，之后编辑不覆盖）；后续事件只碰 updated_at。
func (q *Queries) UpsertCase(ctx context.Context, arg UpsertCaseParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertCase,
		arg.ID,
		arg.RepoID,
		arg.IssueNumber,
		arg.IssueID,
		arg.Title,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
