// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_calls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const incrementModelCallsUsed = `-- name: IncrementModelCallsUsed :execrows
UPDATE runs SET model_calls_used = model_calls_used + 1 WHERE id = $1
`

// 预算护栏：每次模型调用后递增；执行方在下一次调用前检查 used < max。
// 不带 epoch 校验：僵尸的调用也真实花了钱，预算必须如实累计。
func (q *Queries) IncrementModelCallsUsed(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, incrementModelCallsUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertModelCall = `-- name: InsertModelCall :exec
INSERT INTO model_calls (id, run_id, model, input_tokens, output_tokens, cost_cny, cost_status, trace_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertModelCallParams struct {
	ID           string
	RunID        string
	Model        string
	InputTokens  int64
	OutputTokens int64
	CostCny      pgtype.Numeric
	CostStatus   string
	TraceID      *string
}

// model_calls：模型调用与费用（FR-10，AC47）
// 费用记录失败只记日志不失败执行：记账是观测需求，不该比业务更致命。
func (q *Queries) InsertModelCall(ctx context.Context, arg InsertModelCallParams) error {
	_, err := q.db.Exec(ctx, insertModelCall,
		arg.ID,
		arg.RunID,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostCny,
		arg.CostStatus,
		arg.TraceID,
	)
	return err
}
