// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Action struct {
	ID              string
	BundleID        string
	Type            string
	Status          string
	RemoteCommentID *int64
	RemoteUrl       *string
	Receipt         []byte
	Attempts        int32
	CreatedAt       pgtype.Timestamptz
	ExecutedAt      pgtype.Timestamptz
	ReconciledAt    pgtype.Timestamptz
}

type ApprovalBundle struct {
	ID             string
	CaseID         string
	DraftID        string
	ActionType     string
	Target         []byte
	ContentDigest  string
	Status         string
	ExpiresAt      pgtype.Timestamptz
	ApprovedBy     *string
	ApprovedAt     pgtype.Timestamptz
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
}

type Artifact struct {
	ID            string
	RunID         string
	Kind          string
	ContentDigest string
	SizeBytes     int32
	SchemaVersion string
	CreatedAt     pgtype.Timestamptz
}

type Case struct {
	ID           string
	RepoID       string
	IssueNumber  int64
	IssueID      int64
	Title        string
	DisplayState string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type InboxEvent struct {
	ID             string
	DeliveryID     string
	EventType      string
	Action         *string
	RepoNumericID  *int64
	Payload        []byte
	SignatureValid bool
	ProcessStatus  string
	RunID          *string
	ReceivedAt     pgtype.Timestamptz
	ProcessedAt    pgtype.Timestamptz
}

type ModelCall struct {
	ID           string
	RunID        string
	Provider     string
	Model        string
	InputTokens  int64
	OutputTokens int64
	CostCny      pgtype.Numeric
	CostStatus   string
	TraceID      *string
	CreatedAt    pgtype.Timestamptz
}

type Operator struct {
	ID           string
	GithubUserID int64
	DisplayName  *string
	IsAdmin      bool
	CreatedAt    pgtype.Timestamptz
}

type ReplyDraft struct {
	ID                 string
	RunID              string
	ArtifactID         string
	Conclusion         string
	BodyDigest         string
	Evidence           []byte
	NeedsInfoQuestions []byte
	Status             string
	CreatedAt          pgtype.Timestamptz
}

type Repository struct {
	ID             string
	RepoNumericID  int64
	Owner          string
	Name           string
	DefaultBranch  string
	InstallationID int64
	Capabilities   []byte
	PolicyVersion  string
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Run struct {
	ID             string
	CaseID         string
	TriggerEventID string
	InputSnapshot  []byte
	Status         string
	Outcome        *string
	LeaseOwner     *string
	LeaseEpoch     int64
	LeaseExpiresAt pgtype.Timestamptz
	ModelCallsUsed int32
	MaxModelCalls  int32
	Error          *string
	CreatedAt      pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	Attempts       int32
	MaxAttempts    int32
}

type RunCommit struct {
	RunID       string
	CommitID    string
	PayloadHash string
	LeaseEpoch  int64
	Stage       string
	Result      []byte
	Seq         int64
	CreatedAt   pgtype.Timestamptz
}
