// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_api.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentDraftForCaseId = `-- name: GetCurrentDraftForCaseId :one
SELECT r.id, r.run_id, r.artifact_id, r.conclusion, r.body_digest, r.evidence, r.needs_info_questions, r.status, r.created_at FROM reply_drafts r
JOIN runs ru ON r.run_id = ru.id
WHERE ru.case_id = $1 AND r.status = 'current'
ORDER BY r.created_at DESC
LIMIT 1
`

func (q *Queries) GetCurrentDraftForCaseId(ctx context.Context, caseID string) (ReplyDraft, error) {
	row := q.db.QueryRow(ctx, getCurrentDraftForCaseId, caseID)
	var i ReplyDraft
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ArtifactID,
		&i.Conclusion,
		&i.BodyDigest,
		&i.Evidence,
		&i.NeedsInfoQuestions,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listCases = `-- name: ListCases :many
SELECT c.id, c.repo_id, c.issue_number, c.issue_id, c.title, c.display_state, c.created_at, c.updated_at, r.owner AS repo_owner, r.name AS repo_name
FROM cases c JOIN repositories r ON r.id = c.repo_id
ORDER BY c.updated_at DESC
LIMIT 100
`

type ListCasesRow struct {
	ID           string
	RepoID       string
	IssueNumber  int64
	IssueID      int64
	Title        string
	DisplayState string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	RepoOwner    string
	RepoName     string
}

func (q *Queries) ListCases(ctx context.Context) ([]ListCasesRow, error) {
	rows, err := q.db.Query(ctx, listCases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCasesRow
	for rows.Next() {
		var i ListCasesRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.IssueNumber,
			&i.IssueID,
			&i.Title,
			&i.DisplayState,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepoOwner,
			&i.RepoName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelCallsForRun = `-- name: ListModelCallsForRun :many
SELECT id, run_id, provider, model, input_tokens, output_tokens, cost_cny, cost_status, trace_id, created_at FROM model_calls WHERE run_id = $1 ORDER BY created_at
`

func (q *Queries) ListModelCallsForRun(ctx context.Context, runID string) ([]ModelCall, error) {
	rows, err := q.db.Query(ctx, listModelCallsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelCall
	for rows.Next() {
		var i ModelCall
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Provider,
			&i.Model,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostCny,
			&i.CostStatus,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositories = `-- name: ListRepositories :many

SELECT id, repo_numeric_id, owner, name, default_branch, installation_id, capabilities, policy_version, status, created_at, updated_at FROM repositories ORDER BY created_at DESC
`

// 对外查询与接入（T026，US3）
// 只读为主 + 一个最小取消状态机；操作者 API 全部挂 OperatorAuth。
func (q *Queries) ListRepositories(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.RepoNumericID,
			&i.Owner,
			&i.Name,
			&i.DefaultBranch,
			&i.InstallationID,
			&i.Capabilities,
			&i.PolicyVersion,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunCommits = `-- name: ListRunCommits :many
SELECT run_id, commit_id, payload_hash, lease_epoch, stage, result, seq, created_at FROM run_commits WHERE run_id = $1 ORDER BY created_at
`

func (q *Queries) ListRunCommits(ctx context.Context, runID string) ([]RunCommit, error) {
	rows, err := q.db.Query(ctx, listRunCommits, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunCommit
	for rows.Next() {
		var i RunCommit
		if err := rows.Scan(
			&i.RunID,
			&i.CommitID,
			&i.PayloadHash,
			&i.LeaseEpoch,
			&i.Stage,
			&i.Result,
			&i.Seq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForCase = `-- name: ListRunsForCase :many
SELECT id, case_id, trigger_event_id, input_snapshot, status, outcome, lease_owner, lease_epoch, lease_expires_at, model_calls_used, max_model_calls, error, created_at, started_at, finished_at, attempts, max_attempts FROM runs WHERE case_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListRunsForCase(ctx context.Context, caseID string) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsForCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.TriggerEventID,
			&i.InputSnapshot,
			&i.Status,
			&i.Outcome,
			&i.LeaseOwner,
			&i.LeaseEpoch,
			&i.LeaseExpiresAt,
			&i.ModelCallsUsed,
			&i.MaxModelCalls,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Attempts,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestCancelRun = `-- name: RequestCancelRun :execrows
UPDATE runs SET status = CASE
    WHEN status = 'QUEUED' THEN 'CANCELLED'
    WHEN status = 'RUNNING' THEN 'CANCEL_REQUESTED'
    ELSE status
END, finished_at = CASE WHEN status = 'QUEUED' THEN now() ELSE finished_at END
WHERE id = $1 AND status IN ('QUEUED', 'RUNNING')
`

// 取消：QUEUED → CANCELLED 直接终态；RUNNING → CANCEL_REQUESTED 交执行方合作式停止。
func (q *Queries) RequestCancelRun(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, requestCancelRun, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
