// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reply_drafts.sql

package db

import (
	"context"
)

const getCurrentDraftForCase = `-- name: GetCurrentDraftForCase :one
SELECT r.id, r.run_id, r.artifact_id, r.conclusion, r.body_digest, r.evidence, r.needs_info_questions, r.status, r.created_at FROM reply_drafts r
JOIN runs ru ON r.run_id = ru.id
WHERE ru.case_id = $1 AND r.status = 'current'
ORDER BY r.created_at DESC
LIMIT 1
`

func (q *Queries) GetCurrentDraftForCase(ctx context.Context, caseID string) (ReplyDraft, error) {
	row := q.db.QueryRow(ctx, getCurrentDraftForCase, caseID)
	var i ReplyDraft
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ArtifactID,
		&i.Conclusion,
		&i.BodyDigest,
		&i.Evidence,
		&i.NeedsInfoQuestions,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertReplyDraft = `-- name: InsertReplyDraft :exec

INSERT INTO reply_drafts (id, run_id, artifact_id, conclusion, body_digest, evidence, needs_info_questions)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertReplyDraftParams struct {
	ID                 string
	RunID              string
	ArtifactID         string
	Conclusion         string
	BodyDigest         string
	Evidence           []byte
	NeedsInfoQuestions []byte
}

// reply_drafts：答复草稿（审批绑定的内容锚）
// 插入新草稿（status 默认 current）；同 case 旧草稿的 supersede 用独立语句，
// 两者在同一事务里执行（见 SupersedeCaseDrafts）。
func (q *Queries) InsertReplyDraft(ctx context.Context, arg InsertReplyDraftParams) error {
	_, err := q.db.Exec(ctx, insertReplyDraft,
		arg.ID,
		arg.RunID,
		arg.ArtifactID,
		arg.Conclusion,
		arg.BodyDigest,
		arg.Evidence,
		arg.NeedsInfoQuestions,
	)
	return err
}

const supersedeCaseDrafts = `-- name: SupersedeCaseDrafts :execrows
UPDATE reply_drafts SET status = 'superseded'
WHERE status = 'current'
  AND id IN (
    SELECT r.id FROM reply_drafts r
    JOIN runs ru ON r.run_id = ru.id
    WHERE ru.case_id = $1
  )
`

// 同 case 的现有 current 草稿全部翻 superseded：草稿版本「每 case 一个 current」。
// 跨 run 关联需要经过 runs 表（draft 没有 case 列）。
func (q *Queries) SupersedeCaseDrafts(ctx context.Context, caseID string) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeCaseDrafts, caseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
