// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repositories.sql

package db

import (
	"context"
)

const getRepository = `-- name: GetRepository :one
SELECT id, repo_numeric_id, owner, name, default_branch, installation_id, capabilities, policy_version, status, created_at, updated_at FROM repositories WHERE id = $1
`

func (q *Queries) GetRepository(ctx context.Context, id string) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepository, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.RepoNumericID,
		&i.Owner,
		&i.Name,
		&i.DefaultBranch,
		&i.InstallationID,
		&i.Capabilities,
		&i.PolicyVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByNumericID = `-- name: GetRepositoryByNumericID :one

SELECT id, repo_numeric_id, owner, name, default_branch, installation_id, capabilities, policy_version, status, created_at, updated_at FROM repositories WHERE repo_numeric_id = $1
`

// repositories：仓库接入信息
// Webhook 按数字 ID 找仓库（owner/name 可改名，数字 ID 是唯一锚点）。
// 查不到 = 范围外仓库：事件照记（取证），业务忽略。
func (q *Queries) GetRepositoryByNumericID(ctx context.Context, repoNumericID int64) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByNumericID, repoNumericID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.RepoNumericID,
		&i.Owner,
		&i.Name,
		&i.DefaultBranch,
		&i.InstallationID,
		&i.Capabilities,
		&i.PolicyVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
