// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package db

import (
	"context"
)

const claimRun = `-- name: ClaimRun :one

UPDATE runs SET
    status = 'RUNNING',
    lease_owner = $1,
    lease_epoch = lease_epoch + 1,
    lease_expires_at = now() + interval '30 seconds',
    started_at = COALESCE(started_at, now())
WHERE id = (
    SELECT id FROM runs
    WHERE status IN ('QUEUED', 'RECOVERING')
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, case_id, trigger_event_id, input_snapshot, lease_epoch
`

type ClaimRunRow struct {
	ID             string
	CaseID         string
	TriggerEventID string
	InputSnapshot  []byte
	LeaseEpoch     int64
}

// runs：租约协议的全部 SQL（protocol 见 data-model.md，AC23–AC26）
// 领取：单条语句内完成「选行 → 加锁 → 改状态」= 原子领取。
// FOR UPDATE SKIP LOCKED：多个 worker 并发领取时，已被别人锁住的行直接跳过，
// 各拿各的，永不互等（对比：先 SELECT 再 UPDATE 的两步写法在并发下会重复领取）。
// lease_epoch +1：每次交接都换纪元，旧纪元的写回一律拒绝（AC24）。
// 无可领取行时子查询返回 NULL → UPDATE 0 行 → :one 得到 ErrNoRows，worker 据此休眠。
func (q *Queries) ClaimRun(ctx context.Context, leaseOwner *string) (ClaimRunRow, error) {
	row := q.db.QueryRow(ctx, claimRun, leaseOwner)
	var i ClaimRunRow
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.TriggerEventID,
		&i.InputSnapshot,
		&i.LeaseEpoch,
	)
	return i, err
}

const completeRun = `-- name: CompleteRun :execrows
UPDATE runs SET status = 'COMPLETED', outcome = $2, finished_at = now()
WHERE id = $1 AND lease_owner = $3 AND lease_epoch = $4
`

type CompleteRunParams struct {
	ID         string
	Outcome    *string
	LeaseOwner *string
	LeaseEpoch int64
}

// 终态落库：WHERE 双重身份校验，0 行 = 旧 epoch 僵尸写回被拒（AC24）。
func (q *Queries) CompleteRun(ctx context.Context, arg CompleteRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeRun,
		arg.ID,
		arg.Outcome,
		arg.LeaseOwner,
		arg.LeaseEpoch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireStaleRuns = `-- name: ExpireStaleRuns :execrows
UPDATE runs SET status = 'RECOVERING'
WHERE status = 'RUNNING' AND lease_expires_at < now()
`

// 清道夫：租约过期的 RUNNING 统统翻成 RECOVERING，等待被重新领取接管。
// 由 runner 进程周期调用（与领取循环同进程，无需心跳方自己认罪）。
func (q *Queries) ExpireStaleRuns(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireStaleRuns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failRun = `-- name: FailRun :execrows
UPDATE runs SET status = 'FAILED', error = $2, finished_at = now()
WHERE id = $1 AND lease_owner = $3 AND lease_epoch = $4
`

type FailRunParams struct {
	ID         string
	Error      *string
	LeaseOwner *string
	LeaseEpoch int64
}

func (q *Queries) FailRun(ctx context.Context, arg FailRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, failRun,
		arg.ID,
		arg.Error,
		arg.LeaseOwner,
		arg.LeaseEpoch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRun = `-- name: GetRun :one
SELECT id, case_id, trigger_event_id, input_snapshot, status, outcome, lease_owner, lease_epoch, lease_expires_at, model_calls_used, max_model_calls, error, created_at, started_at, finished_at FROM runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.TriggerEventID,
		&i.InputSnapshot,
		&i.Status,
		&i.Outcome,
		&i.LeaseOwner,
		&i.LeaseEpoch,
		&i.LeaseExpiresAt,
		&i.ModelCallsUsed,
		&i.MaxModelCalls,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRunCommitPayloadHash = `-- name: GetRunCommitPayloadHash :one
SELECT payload_hash FROM run_commits
WHERE run_id = $1 AND commit_id = $2
`

type GetRunCommitPayloadHashParams struct {
	RunID    string
	CommitID string
}

func (q *Queries) GetRunCommitPayloadHash(ctx context.Context, arg GetRunCommitPayloadHashParams) (string, error) {
	row := q.db.QueryRow(ctx, getRunCommitPayloadHash, arg.RunID, arg.CommitID)
	var payload_hash string
	err := row.Scan(&payload_hash)
	return payload_hash, err
}

const heartbeatRun = `-- name: HeartbeatRun :execrows
UPDATE runs SET lease_expires_at = now() + interval '30 seconds'
WHERE id = $1 AND lease_owner = $2 AND lease_epoch = $3
`

type HeartbeatRunParams struct {
	ID         string
	LeaseOwner *string
	LeaseEpoch int64
}

// 心跳续租：WHERE 带上 owner+epoch 双重身份。
// 影响行数为 0 = 租约已被服务器易主，持有者必须立刻停止新增工作（PRD §11.3）。
func (q *Queries) HeartbeatRun(ctx context.Context, arg HeartbeatRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatRun, arg.ID, arg.LeaseOwner, arg.LeaseEpoch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRun = `-- name: InsertRun :one
INSERT INTO runs (id, case_id, trigger_event_id, input_snapshot)
VALUES ($1, $2, $3, $4)
RETURNING id, status
`

type InsertRunParams struct {
	ID             string
	CaseID         string
	TriggerEventID string
	InputSnapshot  []byte
}

type InsertRunRow struct {
	ID     string
	Status string
}

// Webhook 同一事务里创建 run：状态默认 QUEUED，等 worker 领取。
// input_snapshot 是触发时刻的固定快照（issue 内容版本 + 策略版本，FR-3），
// 之后无论 Issue 怎么编辑，本次执行都以快照为准。
func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (InsertRunRow, error) {
	row := q.db.QueryRow(ctx, insertRun,
		arg.ID,
		arg.CaseID,
		arg.TriggerEventID,
		arg.InputSnapshot,
	)
	var i InsertRunRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const insertRunCommit = `-- name: InsertRunCommit :one
INSERT INTO run_commits (run_id, commit_id, payload_hash, lease_epoch, stage, result, seq)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (run_id, commit_id) DO NOTHING
RETURNING payload_hash
`

type InsertRunCommitParams struct {
	RunID       string
	CommitID    string
	PayloadHash string
	LeaseEpoch  int64
	Stage       string
	Result      []byte
	Seq         int64
}

// 原子提交回执：同 (run_id, commit_id) 重放 → DO NOTHING（幂等回执，AC25）。
// 冲突时无返回行，controller 再用 GetRunCommitPayloadHash 比对：
// 同 hash = 重放，回执已存在；不同 hash = 同 ID 不同内容，409 冲突（AC26）。
func (q *Queries) InsertRunCommit(ctx context.Context, arg InsertRunCommitParams) (string, error) {
	row := q.db.QueryRow(ctx, insertRunCommit,
		arg.RunID,
		arg.CommitID,
		arg.PayloadHash,
		arg.LeaseEpoch,
		arg.Stage,
		arg.Result,
		arg.Seq,
	)
	var payload_hash string
	err := row.Scan(&payload_hash)
	return payload_hash, err
}
